var annotated_dup =
[
    [ "AccelerationLateralCog", "group___raw_radar_structs.html#struct_acceleration_lateral_cog", "group___raw_radar_structs_struct_acceleration_lateral_cog" ],
    [ "AccelerationLongitudinalCog", "group___raw_radar_structs.html#struct_acceleration_longitudinal_cog", "group___raw_radar_structs_struct_acceleration_longitudinal_cog" ],
    [ "Ars548Detection", "group___raw_radar_structs.html#struct_ars548_detection", "group___raw_radar_structs_struct_ars548_detection" ],
    [ "Ars548DetectionList", "group___raw_radar_structs.html#struct_ars548_detection_list", "group___raw_radar_structs_struct_ars548_detection_list" ],
    [ "Ars548FilterConfigEntry", "group___raw_radar_structs.html#struct_ars548_filter_config_entry", "group___raw_radar_structs_struct_ars548_filter_config_entry" ],
    [ "Ars548FilterConfiguration", "group___raw_radar_structs.html#struct_ars548_filter_configuration", "group___raw_radar_structs_struct_ars548_filter_configuration" ],
    [ "Ars548FilterStatus", "group___raw_radar_structs.html#struct_ars548_filter_status", "group___raw_radar_structs_struct_ars548_filter_status" ],
    [ "Ars548FilterStatusEntry", "group___raw_radar_structs.html#struct_ars548_filter_status_entry", "group___raw_radar_structs_struct_ars548_filter_status_entry" ],
    [ "Ars548Msg", "group___raw_radar_structs.html#struct_ars548_msg", null ],
    [ "Ars548MsgRecord", "struct_ars548_msg_record.html", "struct_ars548_msg_record" ],
    [ "Ars548Object", "group___raw_radar_structs.html#struct_ars548_object", "group___raw_radar_structs_struct_ars548_object" ],
    [ "Ars548ObjectList", "group___raw_radar_structs.html#struct_ars548_object_list", "group___raw_radar_structs_struct_ars548_object_list" ],
    [ "Ars548SensorConfiguration", "group___raw_radar_structs.html#struct_ars548_sensor_configuration", "group___raw_radar_structs_struct_ars548_sensor_configuration" ],
    [ "Ars548SensorStatus", "group___raw_radar_structs.html#struct_ars548_sensor_status", "group___raw_radar_structs_struct_ars548_sensor_status" ],
    [ "Ars548SensorStatusOlder", "group___raw_radar_structs.html#struct_ars548_sensor_status_older", "group___raw_radar_structs_struct_ars548_sensor_status_older" ],
    [ "Ars548TargetRecord", "struct_ars548_target_record.html", "struct_ars548_target_record" ],
    [ "CharacteristicSpeed", "group___raw_radar_structs.html#struct_characteristic_speed", "group___raw_radar_structs_struct_characteristic_speed" ],
    [ "DrivingDirection", "group___raw_radar_structs.html#struct_driving_direction", "group___raw_radar_structs_struct_driving_direction" ],
    [ "E2eP07Header", "group___raw_radar_structs.html#struct_e2e_p07_header", "group___raw_radar_structs_struct_e2e_p07_header" ],
    [ "SomeIPHeader1stPart", "group___raw_radar_structs.html#struct_some_i_p_header1st_part", "group___raw_radar_structs_struct_some_i_p_header1st_part" ],
    [ "SomeIPHeader2ndPart", "group___raw_radar_structs.html#struct_some_i_p_header2nd_part", null ],
    [ "SomeIPPackage", "group___raw_radar_structs.html#struct_some_i_p_package", "group___raw_radar_structs_struct_some_i_p_package" ],
    [ "SteeringAngleFrontAxle", "group___raw_radar_structs.html#struct_steering_angle_front_axle", "group___raw_radar_structs_struct_steering_angle_front_axle" ],
    [ "Target", "group___parsed_structs.html#struct_target", "group___parsed_structs_struct_target" ],
    [ "TargetList", "group___parsed_structs.html#struct_target_list", "group___parsed_structs_struct_target_list" ],
    [ "VehicleDynamicParams", "struct_vehicle_dynamic_params.html", "struct_vehicle_dynamic_params" ],
    [ "VelocityVehicle", "group___raw_radar_structs.html#struct_velocity_vehicle", "group___raw_radar_structs_struct_velocity_vehicle" ],
    [ "YawRate", "group___raw_radar_structs.html#struct_yaw_rate", "group___raw_radar_structs_struct_yaw_rate" ]
];